blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/your-username/restrack/blob/main/README.md
    about: Please check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/your-username/restrack/discussions
    about: Ask questions and discuss ideas with the community
